DocChainWeb/Models/NodeStatusViewModel.cs
using DocChainWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DocChainWeb.Models
{
    public class NodeStatusViewModel
    {
        public List<NetworkNode> Nodes { get; set; }
        public BlockChain Chain { get; set; }
    }
}

DocChainWeb/Controllers/WebAppController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using DocChainWeb.Services;
using DocChainWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace DocChainWeb.Controllers
{
    
    public class WebAppController : Controller
    {
        private readonly ILogger<WebAppController> _logger;
        private readonly ICore _chainService;
        
        private readonly IConfiguration _configuration;
        private readonly IHttpContextAccessor _accessor;

        public WebAppController(
           ILogger<WebAppController> logger,
           ICore core,
           INetworkManager networkManager,
           IConfiguration configuration,
           IHttpContextAccessor accessor
           )
        {
            _logger = logger;
            _chainService = core;
            _configuration = configuration;
            _accessor = accessor;
        }

        public async Task<IActionResult> Index()
        {
            //Retrieve current BlockChain
            var  blockList =await _chainService.GetBlocksList();
            if(blockList.Count <=0 )
            {
                blockList = new List<DataBlock>();
            }

            return View(blockList);
        }

        public async Task<IActionResult> System()
        {
            return View();
        }

        public async Task<IActionResult> NodeStatus()
        {
            NodeStatusViewModel model = new NodeStatusViewModel();
            model.Nodes =await _chainService.GetAllNetworkNodes();   
            model.Chain =await _chainService.GetFullChain();

            return View(model);
        }

        public async Task<IActionResult> CreateTestChain()
        {
            //_chainService.AddTestDocuments(3);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> ResetChain()
        {
            await _chainService.Bootstrap(true);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> BootFromUrl(string bootUrl) {

            bootUrl = $"http://{bootUrl}/";
            if (!String.IsNullOrWhiteSpace(bootUrl))
            {
                var myNode =await _chainService.GetMyChainCredentials();
                //Fill my node from configuration
                myNode.Endpoint =_configuration["NodeIdentification:IPEndpoint"];

                IEnumerable<NetworkNode> remoteNodes =await _chainService.CallWelcomeNode(bootUrl, myNode);

                //IEnumerable<NetworkNode> remoteNodes = _networkManager.CallWelcomeNode(bootUrl, myNode).Result;
                //Add remote credentials to my list
                foreach (var node in remoteNodes)
                {
                    await _chainService.AddNode(node);

                    //_networkManager.AddNode(node);
                }
                NetworkNode bootNode = new NetworkNode()
                {
                    AccessKey = "",
                    Description = "",
                    Endpoint = bootUrl
                };

                //Get Chain
                IEnumerable<DataBlock> chainBlocks =await _chainService.CallGetNodesList(bootNode);

                //IEnumerable<DataBlock> chainBlocks = _networkManager.CallGetNodesList(bootNode).Result;
                //Replace my Chain Nodes
                await _chainService.BootstrapNodes(chainBlocks);
                _logger.LogInformation($"Rebuilding local blockchain");
                //Download Chain to local folder
                foreach (var block in chainBlocks)
                {
                    _logger.LogInformation($"Downloading DocsChain Desc {block.Description}");
                    _logger.LogInformation($"Downloading DocsChain Node {block.Index}");
                    //Download Data from the remote server
                    //var bytesToStore =await _chainService.CallGetDataBlockBytes(block.Index, bootNode);

                    //var bytesToStore = _networkManager.CallGetDataBlockBytes(block.Index, bootNode).Result;

                    //_logger.LogInformation($"{bytesToStore.Length / 1024} KBytes downloaded");

                    //_chainService.StoreBlockBytesToDisk(block.Guid, bytesToStore);
                }
                //Validate The chain
                _logger.LogInformation("Validating downloaded DocsChain...");

                await _chainService.CheckFullChainIntegrity();
            }
            return RedirectToAction("Index");

        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile formFile)
        {
            var fileName = WebUtility.HtmlEncode(Path.GetFileName(formFile.FileName));
            
            var memoryStream = new MemoryStream();
            formFile.CopyTo(memoryStream);
            memoryStream.Seek(0, SeekOrigin.Begin);
            var binaryReader = new BinaryReader(memoryStream);
            var bytes = binaryReader.ReadBytes((int)memoryStream.Length);

            var newBlock =await _chainService.CreateNextBlock(bytes, fileName);

            await _chainService.StoreNewBlockToChain(newBlock);
            
            return RedirectToAction("Index");
        }

        private async Task<string> GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsx", "application/vnd.openxmlformatsofficedocument.spreadsheetml.sheet"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
        }

        [HttpGet]
        public async Task<IActionResult> Download(int Id)
        {
            var blockList = await _chainService.GetFullChain();
            
            var block=blockList.NodesList.Where(x => x.Index == Id).First();
            var nodeBytes = await _chainService.GetDataBlockBytes(block.Guid);

            return File(nodeBytes, await GetContentType(block.Description), block.Description);
        }

        [HttpGet]
        public async Task<string> GetNodeAsBase64(int Id)
        {
            var nodeBytes =await _chainService.GetDataBlockBytes(Id);
            //var sd= Convert.ToBase64String(nodeBytes);
            return Convert.ToBase64String(nodeBytes);
        }
    }
}

DocChainWeb/Views/WebApp/Index.cshtml
@model List<DataBlock>
@{
    ViewData["Title"] = "Documents Blocks";
}

<h3>@ViewData["Title"]</h3>

<form asp-controller="WebApp" asp-action="Upload" method="post" enctype="multipart/form-data">
  <div class="row">
        <div class="col-md-6"></div>

        <div class="col-md-6">
            <div>Submit a Document as new chain Node</div>
            <input type="file" id="formFile" accept=".*" name="formFile" class="btn btn-outline-primary">


            <button type="submit" class="btn btn-outline-primary"> Upload file</button>
        </div>
    </div>

</form>
<br />


<table class="table table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Index</th>
            <th scope="col">Description</th>
            <th scope="col">Data Size</th>
            <th scope="col">Timestamp</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    @if (Model.Count()>0)
    @foreach (var block in Model)
    {
    <tr>
        <td title="Doc Hash: @block.Hash">@block.Index</td>
        <td>@block.Description</td>
        <td>@(block.DataSize / 1024) KBytes</td>
        <td>@block.Timestamp</td>
        <td>
            @if (block.Index != 0 && System.IO.Path.GetExtension(block.Description) == ".*")
            {
                <button type="button" class="btn btn-dark" onclick="ShowPdf('@block.Index')">View Doc</button>
            }
        </td>
        <td>
            @if (block.Index != 0)
            {
                <a href="@Url.Action("Download","WebApp",new {Id=block.Index})"  class="btn btn-dark" >Download</a>
            }
        </td>
    </tr>
    }

</table>


<div id="pdfModalViewer" >
    <!-- data-iziModal-fullscreen="true"  data-iziModal-title="Welcome"  data-iziModal-subtitle="Subtitle"  data-iziModal-icon="icon-home" -->
    <object id="pdfObject" data="" type="application/pdf" width="1100" height="900"></object>
</div>



@section Scripts{ 
    <script>

        $("#pdfModalViewer").iziModal({
            width: 1000,
            height:800,
            transitionIn: 'fadeInLeft',
            transitionOut: 'fadeOutRight'
        });

        function ShowPdf(pdfId) { 
            $.get('/WebApp/GetNodeAsBase64/' + pdfId, function (data) {
                var base64Pdf = "data:application/pdf;base64," + data;
                $("#pdfObject").attr('data', base64Pdf);
                $("#pdfModalViewer").iziModal('open');
            });            
        }
    </script>

}




DocChainWeb/Views/WebApp/NodeStatus.cshtml
@model NodeStatusViewModel
@{
    ViewData["Title"] = "View";
}

<h2>Node Status</h2>

<div class="row">
    <div class="col-md-6">Blockchain Name: <span class="badge badge-success">@Model.Chain.ChainDescription</span></div>
    <div class="col-md-6">Genesis Date: <span class="badge badge-success">@Model.Chain.GenesisDate</span></div>
</div>

<div class="row">
    <div class="col-md-6">Chain Guid: <span class="badge badge-success">@Model.Chain.UniqueId</span></div>
    <div class="col-md-6">Total Nodes: <span class="badge badge-success">@Model.Chain.NodesList.Count</span></div>
</div>

<h3>Connected Peers</h3>
<table class="table table-light">
    <tr>
        <th>Node Name</th>
        <th>Endpoint</th>
    </tr>

    @foreach (var node in Model.Nodes)
    {
    <tr>
        <td>@node.Description</td>
        <td>@node.Endpoint</td>
    </tr>       
    }
</table>



DocChainWeb/Views/WebApp/System.cshtml

@{
    ViewData["Title"] = "System Functions";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-12">
        <form asp-action="BootFromUrl" asp-controller="WebApp">
            <div class="form-group">
                <label for="ipAddress">Known node (live) IP and port (es. 10.175.41.5:5979)</label>
                <input type="text" class="form-control" id="bootUrl" name="bootUrl">
            </div>
            <button type="submit" class="btn btn-primary">Bootstrap Node</button>
        </form>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-12">
        <form asp-action="CreateTestChain" asp-controller="WebApp">
            <div class="form-group">
                <label>Click for upload documents to Blockchain</label>
                <button type="submit" class="btn btn-outline-success">Add New Documents</button>
            </div>  
        </form>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <form asp-action="ResetChain" asp-controller="WebApp">
            <div class="form-group">
                <label>Full Chain Reset</label>
                <button type="submit" class="btn btn-outline-danger">Reset DocsChain Nodes</button>
            </div> 
        </form>
    </div>
</div>